### ISSUE TITLE
Free Camera Not Working - ish.

### ISSUE THREAD

**Issue by Divine-Intervals** [LameGrape/cw-freecam#1]
When using the freecamera mod, pressing M activates it, however the camera is stuck in place and will not move. A little antic I noticed, is when holding W (forward) and M at the same time, makes the player character move forward and your camera is still stuck in place. I've tried to use the hide HUD function aswell, but it too doesn't work.

I've installed this mod using the Thunderstore Mod Manager. I have uninstalled the mod, tried using a different version of it, and keep having the same issue. If you know of any fixes or a possibility of an update to fix this, please let me know. Many thanks!

**Comment by LameGrape** [comment]
Do you have any other mods installed? It might be possible that one is affecting the camera in some way.

**Comment by Divine-Intervals** [comment]
Currently using "Volume Booster" and "Ragdoll Anywhere" as mods.

**Comment by LameGrape** [comment]
The latest release (1.1.2) should hopefully resolve this issue.

**Comment by Divine-Intervals** [comment]
I appreciate you taking the time to check this out, however unfortunately it's still having the same issue. Even removed the cache and reinstalled, making a new profile just for it. Not the world's biggest issue. but hopefully we can figure this out lol
